services:
  aggregator:
    build: ../aggregator
    image: uas-aggregator:latest
    container_name: uas-aggregator
    depends_on:
      storage:
        condition: service_healthy # Menunggu DB siap
      broker:
        condition: service_healthy # Menunggu Redis siap
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    # Menambahkan pengecekan kesehatan aggregator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 5s
      retries: 5

  publisher:
    build: ../publisher
    image: uas-publisher:latest
    container_name: uas-publisher
    depends_on:
      aggregator:
        condition: service_healthy # Publisher HANYA jalan jika aggregator Healthy
    env_file:
      - ../.env
    restart: on-failure # Jika gagal, Docker akan otomatis restart

  broker:
    image: redis:7-alpine
    container_name: uas-broker
    ports:
      - "6379:6379"
    volumes:
      - broker_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  storage:
    image: postgres:16-alpine
    container_name: uas-postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Febriani_20
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
  broker_data: